[package]
name = "karten"
version = "0.1.0"
edition = "2021"
authors = ["Bent Hillerkus"]
repository = "https://github.com/benthillerkus/karten"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
csv = "1.1.6"
mtpng = "0.3.5"
piet-common = { version = "0.6.0" }

[profile.dev.package.mtpng]
opt-level = 3
