[workspace]
members = [
  "karten",
]

[workspace.package]
edition = "2021"
authors = ["Bent Hillerkus"]
repository = "https://github.com/benthillerkus/karten"

[profile.dev.package]
mtpng = { opt-level = 3 }
piet-common = { opt-level = 3 }
