[package]
name = "carp"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
append-only-vec = "0.1.2"
log = { workspace = true }
mtpng = "0.3.5"
piet-common = { workspace = true }
